### ISSUE TITLE
Tạo cơ sở dữ liệu

### ISSUE THREAD

**Issue by vominhquan1995** [vominhquan1995/CCMTPTPM#2]
Thiết kế cơ sở dữ liệu và up lên hệ thống tại brank : Sql

**Comment by nguyenvananhthi** [comment]
da

**Comment by vominhquan1995** [comment]
File scripts chạy data có vấn đề check và cập nhập lại sớm nha Thi

**Comment by nguyenvananhthi** [comment]
File nào Thi hk thấy Q?
Vào 29-12-2016 13:26, "vominhquan1995" <notifications@github.com> đã viết:

**Comment by nguyenvananhthi** [comment]
Đã Nhận

**Comment by vominhquan1995** [comment]
Hoàn tất thiết kế cơ sở dữ liệu

**Comment by nguyenvananhthi** [comment]
Đã nhận
