### ISSUE TITLE
Design layout

### ISSUE THREAD

**Issue by vominhquan1995** [vominhquan1995/CCMTPTPM#3]
Duy và Sang trao đổi thiết kế giao diện chính như đã bàn. Sau đó upload tại nhánh Fontend

**Comment by phanduy1712** [comment]
Đã nhận

**Comment by sangthanh052** [comment]
oke Q

2016-12-28 23:01 GMT+07:00 Phan Quốc Duy <notifications@github.com>:

**Comment by phanduy1712** [comment]
Đã xong
